//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conjuros30
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONJURO
    {
        public long ID_CONJURO { get; set; }
        public string NOMBRE { get; set; }
        public string ESCUELA { get; set; }
        public string NIVEL { get; set; }
        public string COMPONENTES { get; set; }
        public string TIEMPO_LANZAMIENTO { get; set; }
        public string ALCANCE { get; set; }
        public string AREA_EFECTO { get; set; }
        public string DURACION { get; set; }
        public string TIRADA_SALVACION { get; set; }
        public string RESISTENCIA { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
